# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chuby/local_prj/umd-lpc1769/Led_CUBE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chuby/local_prj/umd-lpc1769/Led_CUBE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chuby/local_prj/umd-lpc1769/Led_CUBE/CMakeFiles /home/chuby/local_prj/umd-lpc1769/Led_CUBE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chuby/local_prj/umd-lpc1769/Led_CUBE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Skeleton.axf

# Build rule for target.
Skeleton.axf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Skeleton.axf
.PHONY : Skeleton.axf

# fast build rule for target.
Skeleton.axf/fast:
	$(MAKE) -f CMakeFiles/Skeleton.axf.dir/build.make CMakeFiles/Skeleton.axf.dir/build
.PHONY : Skeleton.axf/fast

#=============================================================================
# Target rules for targets named bin

# Build rule for target.
bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin
.PHONY : bin

# fast build rule for target.
bin/fast:
	$(MAKE) -f CMakeFiles/bin.dir/build.make CMakeFiles/bin.dir/build
.PHONY : bin/fast

#=============================================================================
# Target rules for targets named boot

# Build rule for target.
boot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boot
.PHONY : boot

# fast build rule for target.
boot/fast:
	$(MAKE) -f CMakeFiles/boot.dir/build.make CMakeFiles/boot.dir/build
.PHONY : boot/fast

#=============================================================================
# Target rules for targets named flash

# Build rule for target.
flash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flash
.PHONY : flash

# fast build rule for target.
flash/fast:
	$(MAKE) -f CMakeFiles/flash.dir/build.make CMakeFiles/flash.dir/build
.PHONY : flash/fast

#=============================================================================
# Target rules for targets named flash-halt

# Build rule for target.
flash-halt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flash-halt
.PHONY : flash-halt

# fast build rule for target.
flash-halt/fast:
	$(MAKE) -f CMakeFiles/flash-halt.dir/build.make CMakeFiles/flash-halt.dir/build
.PHONY : flash-halt/fast

#=============================================================================
# Target rules for targets named gdb

# Build rule for target.
gdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gdb
.PHONY : gdb

# fast build rule for target.
gdb/fast:
	$(MAKE) -f CMakeFiles/gdb.dir/build.make CMakeFiles/gdb.dir/build
.PHONY : gdb/fast

#=============================================================================
# Target rules for targets named hex

# Build rule for target.
hex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hex
.PHONY : hex

# fast build rule for target.
hex/fast:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/build
.PHONY : hex/fast

#=============================================================================
# Target rules for targets named lst

# Build rule for target.
lst: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lst
.PHONY : lst

# fast build rule for target.
lst/fast:
	$(MAKE) -f CMakeFiles/lst.dir/build.make CMakeFiles/lst.dir/build
.PHONY : lst/fast

Software/src/cr_startup_lpc176x.obj: Software/src/cr_startup_lpc176x.c.obj
.PHONY : Software/src/cr_startup_lpc176x.obj

# target to build an object file
Software/src/cr_startup_lpc176x.c.obj:
	$(MAKE) -f CMakeFiles/Skeleton.axf.dir/build.make CMakeFiles/Skeleton.axf.dir/Software/src/cr_startup_lpc176x.c.obj
.PHONY : Software/src/cr_startup_lpc176x.c.obj

Software/src/cr_startup_lpc176x.i: Software/src/cr_startup_lpc176x.c.i
.PHONY : Software/src/cr_startup_lpc176x.i

# target to preprocess a source file
Software/src/cr_startup_lpc176x.c.i:
	$(MAKE) -f CMakeFiles/Skeleton.axf.dir/build.make CMakeFiles/Skeleton.axf.dir/Software/src/cr_startup_lpc176x.c.i
.PHONY : Software/src/cr_startup_lpc176x.c.i

Software/src/cr_startup_lpc176x.s: Software/src/cr_startup_lpc176x.c.s
.PHONY : Software/src/cr_startup_lpc176x.s

# target to generate assembly for a file
Software/src/cr_startup_lpc176x.c.s:
	$(MAKE) -f CMakeFiles/Skeleton.axf.dir/build.make CMakeFiles/Skeleton.axf.dir/Software/src/cr_startup_lpc176x.c.s
.PHONY : Software/src/cr_startup_lpc176x.c.s

Software/src/main.obj: Software/src/main.c.obj
.PHONY : Software/src/main.obj

# target to build an object file
Software/src/main.c.obj:
	$(MAKE) -f CMakeFiles/Skeleton.axf.dir/build.make CMakeFiles/Skeleton.axf.dir/Software/src/main.c.obj
.PHONY : Software/src/main.c.obj

Software/src/main.i: Software/src/main.c.i
.PHONY : Software/src/main.i

# target to preprocess a source file
Software/src/main.c.i:
	$(MAKE) -f CMakeFiles/Skeleton.axf.dir/build.make CMakeFiles/Skeleton.axf.dir/Software/src/main.c.i
.PHONY : Software/src/main.c.i

Software/src/main.s: Software/src/main.c.s
.PHONY : Software/src/main.s

# target to generate assembly for a file
Software/src/main.c.s:
	$(MAKE) -f CMakeFiles/Skeleton.axf.dir/build.make CMakeFiles/Skeleton.axf.dir/Software/src/main.c.s
.PHONY : Software/src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Skeleton.axf"
	@echo "... bin"
	@echo "... boot"
	@echo "... edit_cache"
	@echo "... flash"
	@echo "... flash-halt"
	@echo "... gdb"
	@echo "... hex"
	@echo "... lst"
	@echo "... rebuild_cache"
	@echo "... Software/src/cr_startup_lpc176x.obj"
	@echo "... Software/src/cr_startup_lpc176x.i"
	@echo "... Software/src/cr_startup_lpc176x.s"
	@echo "... Software/src/main.obj"
	@echo "... Software/src/main.i"
	@echo "... Software/src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

