# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chuby/local_prj/umd-lpc1769/Led_CUBE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chuby/local_prj/umd-lpc1769/Led_CUBE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chuby/local_prj/umd-lpc1769/Led_CUBE/CMakeFiles /home/chuby/local_prj/umd-lpc1769/Led_CUBE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chuby/local_prj/umd-lpc1769/Led_CUBE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Led_CUBE.axf

# Build rule for target.
Led_CUBE.axf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Led_CUBE.axf
.PHONY : Led_CUBE.axf

# fast build rule for target.
Led_CUBE.axf/fast:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/build
.PHONY : Led_CUBE.axf/fast

#=============================================================================
# Target rules for targets named bin

# Build rule for target.
bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin
.PHONY : bin

# fast build rule for target.
bin/fast:
	$(MAKE) -f CMakeFiles/bin.dir/build.make CMakeFiles/bin.dir/build
.PHONY : bin/fast

#=============================================================================
# Target rules for targets named boot

# Build rule for target.
boot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boot
.PHONY : boot

# fast build rule for target.
boot/fast:
	$(MAKE) -f CMakeFiles/boot.dir/build.make CMakeFiles/boot.dir/build
.PHONY : boot/fast

#=============================================================================
# Target rules for targets named flash

# Build rule for target.
flash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flash
.PHONY : flash

# fast build rule for target.
flash/fast:
	$(MAKE) -f CMakeFiles/flash.dir/build.make CMakeFiles/flash.dir/build
.PHONY : flash/fast

#=============================================================================
# Target rules for targets named flash-halt

# Build rule for target.
flash-halt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flash-halt
.PHONY : flash-halt

# fast build rule for target.
flash-halt/fast:
	$(MAKE) -f CMakeFiles/flash-halt.dir/build.make CMakeFiles/flash-halt.dir/build
.PHONY : flash-halt/fast

#=============================================================================
# Target rules for targets named gdb

# Build rule for target.
gdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gdb
.PHONY : gdb

# fast build rule for target.
gdb/fast:
	$(MAKE) -f CMakeFiles/gdb.dir/build.make CMakeFiles/gdb.dir/build
.PHONY : gdb/fast

#=============================================================================
# Target rules for targets named hex

# Build rule for target.
hex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hex
.PHONY : hex

# fast build rule for target.
hex/fast:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/build
.PHONY : hex/fast

#=============================================================================
# Target rules for targets named lst

# Build rule for target.
lst: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lst
.PHONY : lst

# fast build rule for target.
lst/fast:
	$(MAKE) -f CMakeFiles/lst.dir/build.make CMakeFiles/lst.dir/build
.PHONY : lst/fast

Software/FastPWM/FastPWM.obj: Software/FastPWM/FastPWM.c.obj
.PHONY : Software/FastPWM/FastPWM.obj

# target to build an object file
Software/FastPWM/FastPWM.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/FastPWM/FastPWM.c.obj
.PHONY : Software/FastPWM/FastPWM.c.obj

Software/FastPWM/FastPWM.i: Software/FastPWM/FastPWM.c.i
.PHONY : Software/FastPWM/FastPWM.i

# target to preprocess a source file
Software/FastPWM/FastPWM.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/FastPWM/FastPWM.c.i
.PHONY : Software/FastPWM/FastPWM.c.i

Software/FastPWM/FastPWM.s: Software/FastPWM/FastPWM.c.s
.PHONY : Software/FastPWM/FastPWM.s

# target to generate assembly for a file
Software/FastPWM/FastPWM.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/FastPWM/FastPWM.c.s
.PHONY : Software/FastPWM/FastPWM.c.s

Software/LEDCUBE/ColourWheel.obj: Software/LEDCUBE/ColourWheel.c.obj
.PHONY : Software/LEDCUBE/ColourWheel.obj

# target to build an object file
Software/LEDCUBE/ColourWheel.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/ColourWheel.c.obj
.PHONY : Software/LEDCUBE/ColourWheel.c.obj

Software/LEDCUBE/ColourWheel.i: Software/LEDCUBE/ColourWheel.c.i
.PHONY : Software/LEDCUBE/ColourWheel.i

# target to preprocess a source file
Software/LEDCUBE/ColourWheel.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/ColourWheel.c.i
.PHONY : Software/LEDCUBE/ColourWheel.c.i

Software/LEDCUBE/ColourWheel.s: Software/LEDCUBE/ColourWheel.c.s
.PHONY : Software/LEDCUBE/ColourWheel.s

# target to generate assembly for a file
Software/LEDCUBE/ColourWheel.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/ColourWheel.c.s
.PHONY : Software/LEDCUBE/ColourWheel.c.s

Software/LEDCUBE/ledcube.obj: Software/LEDCUBE/ledcube.c.obj
.PHONY : Software/LEDCUBE/ledcube.obj

# target to build an object file
Software/LEDCUBE/ledcube.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/ledcube.c.obj
.PHONY : Software/LEDCUBE/ledcube.c.obj

Software/LEDCUBE/ledcube.i: Software/LEDCUBE/ledcube.c.i
.PHONY : Software/LEDCUBE/ledcube.i

# target to preprocess a source file
Software/LEDCUBE/ledcube.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/ledcube.c.i
.PHONY : Software/LEDCUBE/ledcube.c.i

Software/LEDCUBE/ledcube.s: Software/LEDCUBE/ledcube.c.s
.PHONY : Software/LEDCUBE/ledcube.s

# target to generate assembly for a file
Software/LEDCUBE/ledcube.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/ledcube.c.s
.PHONY : Software/LEDCUBE/ledcube.c.s

Software/LEDCUBE/sinWave.obj: Software/LEDCUBE/sinWave.c.obj
.PHONY : Software/LEDCUBE/sinWave.obj

# target to build an object file
Software/LEDCUBE/sinWave.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/sinWave.c.obj
.PHONY : Software/LEDCUBE/sinWave.c.obj

Software/LEDCUBE/sinWave.i: Software/LEDCUBE/sinWave.c.i
.PHONY : Software/LEDCUBE/sinWave.i

# target to preprocess a source file
Software/LEDCUBE/sinWave.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/sinWave.c.i
.PHONY : Software/LEDCUBE/sinWave.c.i

Software/LEDCUBE/sinWave.s: Software/LEDCUBE/sinWave.c.s
.PHONY : Software/LEDCUBE/sinWave.s

# target to generate assembly for a file
Software/LEDCUBE/sinWave.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/sinWave.c.s
.PHONY : Software/LEDCUBE/sinWave.c.s

Software/LEDCUBE/spiral.obj: Software/LEDCUBE/spiral.c.obj
.PHONY : Software/LEDCUBE/spiral.obj

# target to build an object file
Software/LEDCUBE/spiral.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/spiral.c.obj
.PHONY : Software/LEDCUBE/spiral.c.obj

Software/LEDCUBE/spiral.i: Software/LEDCUBE/spiral.c.i
.PHONY : Software/LEDCUBE/spiral.i

# target to preprocess a source file
Software/LEDCUBE/spiral.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/spiral.c.i
.PHONY : Software/LEDCUBE/spiral.c.i

Software/LEDCUBE/spiral.s: Software/LEDCUBE/spiral.c.s
.PHONY : Software/LEDCUBE/spiral.s

# target to generate assembly for a file
Software/LEDCUBE/spiral.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/spiral.c.s
.PHONY : Software/LEDCUBE/spiral.c.s

Software/LEDCUBE/utils.obj: Software/LEDCUBE/utils.c.obj
.PHONY : Software/LEDCUBE/utils.obj

# target to build an object file
Software/LEDCUBE/utils.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/utils.c.obj
.PHONY : Software/LEDCUBE/utils.c.obj

Software/LEDCUBE/utils.i: Software/LEDCUBE/utils.c.i
.PHONY : Software/LEDCUBE/utils.i

# target to preprocess a source file
Software/LEDCUBE/utils.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/utils.c.i
.PHONY : Software/LEDCUBE/utils.c.i

Software/LEDCUBE/utils.s: Software/LEDCUBE/utils.c.s
.PHONY : Software/LEDCUBE/utils.s

# target to generate assembly for a file
Software/LEDCUBE/utils.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/LEDCUBE/utils.c.s
.PHONY : Software/LEDCUBE/utils.c.s

Software/SPI_SSP/spi.obj: Software/SPI_SSP/spi.c.obj
.PHONY : Software/SPI_SSP/spi.obj

# target to build an object file
Software/SPI_SSP/spi.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/SPI_SSP/spi.c.obj
.PHONY : Software/SPI_SSP/spi.c.obj

Software/SPI_SSP/spi.i: Software/SPI_SSP/spi.c.i
.PHONY : Software/SPI_SSP/spi.i

# target to preprocess a source file
Software/SPI_SSP/spi.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/SPI_SSP/spi.c.i
.PHONY : Software/SPI_SSP/spi.c.i

Software/SPI_SSP/spi.s: Software/SPI_SSP/spi.c.s
.PHONY : Software/SPI_SSP/spi.s

# target to generate assembly for a file
Software/SPI_SSP/spi.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/SPI_SSP/spi.c.s
.PHONY : Software/SPI_SSP/spi.c.s

Software/TLC5940/TLC5940.obj: Software/TLC5940/TLC5940.c.obj
.PHONY : Software/TLC5940/TLC5940.obj

# target to build an object file
Software/TLC5940/TLC5940.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/TLC5940/TLC5940.c.obj
.PHONY : Software/TLC5940/TLC5940.c.obj

Software/TLC5940/TLC5940.i: Software/TLC5940/TLC5940.c.i
.PHONY : Software/TLC5940/TLC5940.i

# target to preprocess a source file
Software/TLC5940/TLC5940.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/TLC5940/TLC5940.c.i
.PHONY : Software/TLC5940/TLC5940.c.i

Software/TLC5940/TLC5940.s: Software/TLC5940/TLC5940.c.s
.PHONY : Software/TLC5940/TLC5940.s

# target to generate assembly for a file
Software/TLC5940/TLC5940.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/TLC5940/TLC5940.c.s
.PHONY : Software/TLC5940/TLC5940.c.s

Software/liblpc-src/lpc17xx_clkpwr.obj: Software/liblpc-src/lpc17xx_clkpwr.c.obj
.PHONY : Software/liblpc-src/lpc17xx_clkpwr.obj

# target to build an object file
Software/liblpc-src/lpc17xx_clkpwr.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_clkpwr.c.obj
.PHONY : Software/liblpc-src/lpc17xx_clkpwr.c.obj

Software/liblpc-src/lpc17xx_clkpwr.i: Software/liblpc-src/lpc17xx_clkpwr.c.i
.PHONY : Software/liblpc-src/lpc17xx_clkpwr.i

# target to preprocess a source file
Software/liblpc-src/lpc17xx_clkpwr.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_clkpwr.c.i
.PHONY : Software/liblpc-src/lpc17xx_clkpwr.c.i

Software/liblpc-src/lpc17xx_clkpwr.s: Software/liblpc-src/lpc17xx_clkpwr.c.s
.PHONY : Software/liblpc-src/lpc17xx_clkpwr.s

# target to generate assembly for a file
Software/liblpc-src/lpc17xx_clkpwr.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_clkpwr.c.s
.PHONY : Software/liblpc-src/lpc17xx_clkpwr.c.s

Software/liblpc-src/lpc17xx_gpdma.obj: Software/liblpc-src/lpc17xx_gpdma.c.obj
.PHONY : Software/liblpc-src/lpc17xx_gpdma.obj

# target to build an object file
Software/liblpc-src/lpc17xx_gpdma.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_gpdma.c.obj
.PHONY : Software/liblpc-src/lpc17xx_gpdma.c.obj

Software/liblpc-src/lpc17xx_gpdma.i: Software/liblpc-src/lpc17xx_gpdma.c.i
.PHONY : Software/liblpc-src/lpc17xx_gpdma.i

# target to preprocess a source file
Software/liblpc-src/lpc17xx_gpdma.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_gpdma.c.i
.PHONY : Software/liblpc-src/lpc17xx_gpdma.c.i

Software/liblpc-src/lpc17xx_gpdma.s: Software/liblpc-src/lpc17xx_gpdma.c.s
.PHONY : Software/liblpc-src/lpc17xx_gpdma.s

# target to generate assembly for a file
Software/liblpc-src/lpc17xx_gpdma.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_gpdma.c.s
.PHONY : Software/liblpc-src/lpc17xx_gpdma.c.s

Software/liblpc-src/lpc17xx_libcfg_default.obj: Software/liblpc-src/lpc17xx_libcfg_default.c.obj
.PHONY : Software/liblpc-src/lpc17xx_libcfg_default.obj

# target to build an object file
Software/liblpc-src/lpc17xx_libcfg_default.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_libcfg_default.c.obj
.PHONY : Software/liblpc-src/lpc17xx_libcfg_default.c.obj

Software/liblpc-src/lpc17xx_libcfg_default.i: Software/liblpc-src/lpc17xx_libcfg_default.c.i
.PHONY : Software/liblpc-src/lpc17xx_libcfg_default.i

# target to preprocess a source file
Software/liblpc-src/lpc17xx_libcfg_default.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_libcfg_default.c.i
.PHONY : Software/liblpc-src/lpc17xx_libcfg_default.c.i

Software/liblpc-src/lpc17xx_libcfg_default.s: Software/liblpc-src/lpc17xx_libcfg_default.c.s
.PHONY : Software/liblpc-src/lpc17xx_libcfg_default.s

# target to generate assembly for a file
Software/liblpc-src/lpc17xx_libcfg_default.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_libcfg_default.c.s
.PHONY : Software/liblpc-src/lpc17xx_libcfg_default.c.s

Software/liblpc-src/lpc17xx_pinsel.obj: Software/liblpc-src/lpc17xx_pinsel.c.obj
.PHONY : Software/liblpc-src/lpc17xx_pinsel.obj

# target to build an object file
Software/liblpc-src/lpc17xx_pinsel.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_pinsel.c.obj
.PHONY : Software/liblpc-src/lpc17xx_pinsel.c.obj

Software/liblpc-src/lpc17xx_pinsel.i: Software/liblpc-src/lpc17xx_pinsel.c.i
.PHONY : Software/liblpc-src/lpc17xx_pinsel.i

# target to preprocess a source file
Software/liblpc-src/lpc17xx_pinsel.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_pinsel.c.i
.PHONY : Software/liblpc-src/lpc17xx_pinsel.c.i

Software/liblpc-src/lpc17xx_pinsel.s: Software/liblpc-src/lpc17xx_pinsel.c.s
.PHONY : Software/liblpc-src/lpc17xx_pinsel.s

# target to generate assembly for a file
Software/liblpc-src/lpc17xx_pinsel.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_pinsel.c.s
.PHONY : Software/liblpc-src/lpc17xx_pinsel.c.s

Software/liblpc-src/lpc17xx_pwm.obj: Software/liblpc-src/lpc17xx_pwm.c.obj
.PHONY : Software/liblpc-src/lpc17xx_pwm.obj

# target to build an object file
Software/liblpc-src/lpc17xx_pwm.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_pwm.c.obj
.PHONY : Software/liblpc-src/lpc17xx_pwm.c.obj

Software/liblpc-src/lpc17xx_pwm.i: Software/liblpc-src/lpc17xx_pwm.c.i
.PHONY : Software/liblpc-src/lpc17xx_pwm.i

# target to preprocess a source file
Software/liblpc-src/lpc17xx_pwm.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_pwm.c.i
.PHONY : Software/liblpc-src/lpc17xx_pwm.c.i

Software/liblpc-src/lpc17xx_pwm.s: Software/liblpc-src/lpc17xx_pwm.c.s
.PHONY : Software/liblpc-src/lpc17xx_pwm.s

# target to generate assembly for a file
Software/liblpc-src/lpc17xx_pwm.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_pwm.c.s
.PHONY : Software/liblpc-src/lpc17xx_pwm.c.s

Software/liblpc-src/lpc17xx_ssp.obj: Software/liblpc-src/lpc17xx_ssp.c.obj
.PHONY : Software/liblpc-src/lpc17xx_ssp.obj

# target to build an object file
Software/liblpc-src/lpc17xx_ssp.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_ssp.c.obj
.PHONY : Software/liblpc-src/lpc17xx_ssp.c.obj

Software/liblpc-src/lpc17xx_ssp.i: Software/liblpc-src/lpc17xx_ssp.c.i
.PHONY : Software/liblpc-src/lpc17xx_ssp.i

# target to preprocess a source file
Software/liblpc-src/lpc17xx_ssp.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_ssp.c.i
.PHONY : Software/liblpc-src/lpc17xx_ssp.c.i

Software/liblpc-src/lpc17xx_ssp.s: Software/liblpc-src/lpc17xx_ssp.c.s
.PHONY : Software/liblpc-src/lpc17xx_ssp.s

# target to generate assembly for a file
Software/liblpc-src/lpc17xx_ssp.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/liblpc-src/lpc17xx_ssp.c.s
.PHONY : Software/liblpc-src/lpc17xx_ssp.c.s

Software/src/cr_startup_lpc176x.obj: Software/src/cr_startup_lpc176x.c.obj
.PHONY : Software/src/cr_startup_lpc176x.obj

# target to build an object file
Software/src/cr_startup_lpc176x.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/src/cr_startup_lpc176x.c.obj
.PHONY : Software/src/cr_startup_lpc176x.c.obj

Software/src/cr_startup_lpc176x.i: Software/src/cr_startup_lpc176x.c.i
.PHONY : Software/src/cr_startup_lpc176x.i

# target to preprocess a source file
Software/src/cr_startup_lpc176x.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/src/cr_startup_lpc176x.c.i
.PHONY : Software/src/cr_startup_lpc176x.c.i

Software/src/cr_startup_lpc176x.s: Software/src/cr_startup_lpc176x.c.s
.PHONY : Software/src/cr_startup_lpc176x.s

# target to generate assembly for a file
Software/src/cr_startup_lpc176x.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/src/cr_startup_lpc176x.c.s
.PHONY : Software/src/cr_startup_lpc176x.c.s

Software/src/main.obj: Software/src/main.c.obj
.PHONY : Software/src/main.obj

# target to build an object file
Software/src/main.c.obj:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/src/main.c.obj
.PHONY : Software/src/main.c.obj

Software/src/main.i: Software/src/main.c.i
.PHONY : Software/src/main.i

# target to preprocess a source file
Software/src/main.c.i:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/src/main.c.i
.PHONY : Software/src/main.c.i

Software/src/main.s: Software/src/main.c.s
.PHONY : Software/src/main.s

# target to generate assembly for a file
Software/src/main.c.s:
	$(MAKE) -f CMakeFiles/Led_CUBE.axf.dir/build.make CMakeFiles/Led_CUBE.axf.dir/Software/src/main.c.s
.PHONY : Software/src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Led_CUBE.axf"
	@echo "... bin"
	@echo "... boot"
	@echo "... edit_cache"
	@echo "... flash"
	@echo "... flash-halt"
	@echo "... gdb"
	@echo "... hex"
	@echo "... lst"
	@echo "... rebuild_cache"
	@echo "... Software/FastPWM/FastPWM.obj"
	@echo "... Software/FastPWM/FastPWM.i"
	@echo "... Software/FastPWM/FastPWM.s"
	@echo "... Software/LEDCUBE/ColourWheel.obj"
	@echo "... Software/LEDCUBE/ColourWheel.i"
	@echo "... Software/LEDCUBE/ColourWheel.s"
	@echo "... Software/LEDCUBE/ledcube.obj"
	@echo "... Software/LEDCUBE/ledcube.i"
	@echo "... Software/LEDCUBE/ledcube.s"
	@echo "... Software/LEDCUBE/sinWave.obj"
	@echo "... Software/LEDCUBE/sinWave.i"
	@echo "... Software/LEDCUBE/sinWave.s"
	@echo "... Software/LEDCUBE/spiral.obj"
	@echo "... Software/LEDCUBE/spiral.i"
	@echo "... Software/LEDCUBE/spiral.s"
	@echo "... Software/LEDCUBE/utils.obj"
	@echo "... Software/LEDCUBE/utils.i"
	@echo "... Software/LEDCUBE/utils.s"
	@echo "... Software/SPI_SSP/spi.obj"
	@echo "... Software/SPI_SSP/spi.i"
	@echo "... Software/SPI_SSP/spi.s"
	@echo "... Software/TLC5940/TLC5940.obj"
	@echo "... Software/TLC5940/TLC5940.i"
	@echo "... Software/TLC5940/TLC5940.s"
	@echo "... Software/liblpc-src/lpc17xx_clkpwr.obj"
	@echo "... Software/liblpc-src/lpc17xx_clkpwr.i"
	@echo "... Software/liblpc-src/lpc17xx_clkpwr.s"
	@echo "... Software/liblpc-src/lpc17xx_gpdma.obj"
	@echo "... Software/liblpc-src/lpc17xx_gpdma.i"
	@echo "... Software/liblpc-src/lpc17xx_gpdma.s"
	@echo "... Software/liblpc-src/lpc17xx_libcfg_default.obj"
	@echo "... Software/liblpc-src/lpc17xx_libcfg_default.i"
	@echo "... Software/liblpc-src/lpc17xx_libcfg_default.s"
	@echo "... Software/liblpc-src/lpc17xx_pinsel.obj"
	@echo "... Software/liblpc-src/lpc17xx_pinsel.i"
	@echo "... Software/liblpc-src/lpc17xx_pinsel.s"
	@echo "... Software/liblpc-src/lpc17xx_pwm.obj"
	@echo "... Software/liblpc-src/lpc17xx_pwm.i"
	@echo "... Software/liblpc-src/lpc17xx_pwm.s"
	@echo "... Software/liblpc-src/lpc17xx_ssp.obj"
	@echo "... Software/liblpc-src/lpc17xx_ssp.i"
	@echo "... Software/liblpc-src/lpc17xx_ssp.s"
	@echo "... Software/src/cr_startup_lpc176x.obj"
	@echo "... Software/src/cr_startup_lpc176x.i"
	@echo "... Software/src/cr_startup_lpc176x.s"
	@echo "... Software/src/main.obj"
	@echo "... Software/src/main.i"
	@echo "... Software/src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

